#!/usr/bin/env sh

cmd=$(grep -h '^Exec=' {~/.local,~/.nix-profile,/usr}/share/applications/"$browser" 2>/dev/null | head -1 | cut -d= -f2)

if [ -z "$cmd" ]; then
  cmd="chromium"
fi

cmd=$(printf '%s\n' "$cmd" | sed 's/ *%[fFuUdDnNickvm]//g')

echo "Browser: $browser"
echo "Command: $cmd"

echo "exec: setsid uwsm-app -- $cmd --app="$1" "${@:2}""

exec setsid uwsm-app -- $cmd --app="$1" "${@:2}"
